#!/bin/sh
set -e
exec 3>&1
exec 1>&2
readonly TMPDIR=/tmp
readonly PAYLOAD=$(mktemp -u $TMPDIR/resource-salt-pepper_request.XXXXXXXX)
readonly RESOURCE_RESPONSE=$(mktemp -u $TMPDIR/resource-salt-pepper_response.XXXXXXXX)
readonly SOURCE=$1
tee "$PAYLOAD" | concsp out "$SOURCE" | tee "$RESOURCE_RESPONSE" >&3
