source_repository_git_workflow_image: "docker.domain.tld/concourse/resource/git-workflow"
project_name: "concourse-salt-pepper"
source_uri: "git@git.domain.tld:concourse-salt-pepper" 
smtp_host: "smtp.domain.tld" 
smtp_from: "concourse-build@domain.tld" 
smtp_to: "build@domain.tld" 
repository_build_image: "docker.domain.tld/concourse/resource/salt-pepper"
http_proxy: "http://proxy.domain.tld:3128"
